http://localhost:5000/

###
POST http://localhost:5000/admin/register
Content-Type: application/json

{
    "name": "Mital",
    "email": "mital@gmail.com",
    "password": "123456"
}

###
POST http://localhost:5000/admin/login
Content-Type: application/json

{
    "email": "mital@gmail.com",
    "password": "123456"
}


###
POST http://localhost:5000/admin/refresh
Content-Type: application/json



###
POST http://localhost:5000/post/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6eyJfaWQiOiI2NTAxNDBlODg4NjljZWQ1MmVmNDk5YzkiLCJuYW1lIjoiTWl0YWwiLCJlbWFpbCI6Im1pdGFsQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJHVPV2lJZlBuaktuVlBlNHgzUFowRS5KMk92ZkVUSUlPOVF1NVEvdVRjdWdQY2NvV2x6TDhLIiwiY3JlYXRlZCI6IjIwMjMtMDktMTNUMDQ6NTY6MDQuNDcxWiIsIl9fdiI6MH0sImlhdCI6MTY5NDY2NTEwNiwiZXhwIjoxNjk0NjY1MTY2fQ.dzqOsUFRouuC0EcOdHcsj0gqIksacNQvHBHSFuOAfMQ


{
    "title": "title rertrert"
}


